spring:
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

#自定义数据源配置
#主数据源（druid要求多数据源配置必须标注主数据源）
primary:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.mysql.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://119.23.204.78:3306/ds_0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20

#从数据源
back:
  datasource:
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.mysql.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://119.23.204.78:3306/ds_1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
#
#shardingRule:
#  tables:
#    t_order:
#      actualDataNodes: ds${0..1}.t_order${0..1}
#      databaseStrategy:
#        inline:
#          shardingColumn: user_id
#          algorithmInlineExpression: ds${user_id % 2}
#      tableStrategy:
#        inline:
#          shardingColumn: order_id
#          algorithmInlineExpression: t_order${order_id % 2}
#    t_order_item:
#      actualDataNodes: ds${0..1}.t_order_item${0..1}
#      databaseStrategy:
#        inline:
#          shardingColumn: user_id
#          algorithmInlineExpression: ds${user_id % 2}
#      tableStrategy:
#        inline:
#          shardingColumn: order_id
#          algorithmInlineExpression: t_order_item${order_id % 2}